import './globals.css'
import type { Metadata } from 'next'
import Providers from './components/Providers'
import Sidebar from './components/Sidebar'
import { ThemeProvider } from '@/components/theme-provider'
// import { Inter } from 'next/font/google'
// import Topbar from './components/Topbar'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="h-screen" suppressHydrationWarning>
      <body className="flex flex-row h-full">
        <ThemeProvider>
          <Providers>
            {/* <Topbar /> */}
            <Sidebar className="max-w-[1/6] bg-[#CE7178] top-0 botton-0 rounded-md" />
            <div className="overflow-y-scroll">{children}</div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
